[package]
name = "quirl-ui"
description = "Quirl's semantic prompt, completion menu, and diagnostics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
crossterm.workspace = true
nu-ansi-term.workspace = true
quirl-catalog = { path = "../quirl-catalog" }
quirl-core = { path = "../quirl-core" }
quirl-lua = { path = "../quirl-lua" }
quirl-picker = { path = "../quirl-picker" }
quirl-syntax = { path = "../quirl-syntax" }
reedline = { workspace = true, features = ["helix"] }
serde.workspace = true
serde_json.workspace = true
