use clap::{Subcommand, ValueEnum};
use quirl_catalog::Catalog;
use quirl_contract::{
    build_agent_catalog, build_agent_context, build_agent_manifest, render_context_markdown,
    validate_agent_document_with_anchors, AgentCatalog, AgentDocumentKind, AgentManifest,
    AgentValidationAnchors, HostCapability, HostParameter, ValidationReport, DEFAULT_TOKEN_BUDGET,
};
use quirl_core::{ErrorCode, ShellError};
use quirl_lua::HOST_API;
use serde::Serialize;
use std::{
    fs,
    path::{Path, PathBuf},
};

#[derive(Debug, Subcommand)]
pub enum AgentCommand {
    /// Export the installed command and Lua host capability catalog.
    Catalog {
        #[arg(long, value_enum, default_value_t = AgentOutputFormat::Json)]
        format: AgentOutputFormat,
    },
    /// Select the smallest relevant installed subtree within a deterministic budget.
    Context {
        #[arg(required = true, num_args = 1..)]
        query: Vec<String>,
        #[arg(long, default_value_t = DEFAULT_TOKEN_BUDGET)]
        token_budget: usize,
        #[arg(long, value_enum, default_value_t = ContextOutputFormat::Markdown)]
        format: ContextOutputFormat,
    },
    /// Export installed versions, schema hashes, capabilities, tools, and validators.
    Manifest {
        #[arg(long, value_enum, default_value_t = AgentOutputFormat::Json)]
        format: AgentOutputFormat,
    },
    /// Validate a versioned agent document without executing code.
    Validate {
        file: PathBuf,
        #[arg(long, value_enum)]
        kind: AgentKind,
        #[arg(long, value_enum, default_value_t = AgentOutputFormat::Text)]
        format: AgentOutputFormat,
    },
}

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum AgentOutputFormat {
    Text,
    Json,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum ContextOutputFormat {
    Markdown,
    Json,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum AgentKind {
    Catalog,
    Context,
    Manifest,
}

pub fn wants_json(command: &AgentCommand) -> bool {
    matches!(
        command,
        AgentCommand::Catalog {
            format: AgentOutputFormat::Json
        } | AgentCommand::Context {
            format: ContextOutputFormat::Json,
            ..
        } | AgentCommand::Manifest {
            format: AgentOutputFormat::Json
        } | AgentCommand::Validate {
            format: AgentOutputFormat::Json,
            ..
        }
    )
}

pub fn execute(command: AgentCommand, catalog: &Catalog) -> Result<i32, ShellError> {
    match command {
        AgentCommand::Catalog { format } => {
            let catalog = installed_agent_catalog(catalog)?;
            match format {
                AgentOutputFormat::Json => print_json(&catalog)?,
                AgentOutputFormat::Text => print_agent_catalog(&catalog),
            }
            Ok(0)
        }
        AgentCommand::Context {
            query,
            token_budget,
            format,
        } => {
            let catalog = installed_agent_catalog(catalog)?;
            let context = build_agent_context(&catalog, &query.join(" "), token_budget)?;
            match format {
                ContextOutputFormat::Json => print_json(&context)?,
                ContextOutputFormat::Markdown => print!("{}", render_context_markdown(&context)),
            }
            Ok(0)
        }
        AgentCommand::Manifest { format } => {
            let catalog = installed_agent_catalog(catalog)?;
            let manifest = build_agent_manifest(&catalog)?;
            match format {
                AgentOutputFormat::Json => print_json(&manifest)?,
                AgentOutputFormat::Text => print_agent_manifest(&manifest),
            }
            Ok(0)
        }
        AgentCommand::Validate { file, kind, format } => {
            let source = fs::read(&file).map_err(|error| {
                ShellError::new(
                    ErrorCode::Io,
                    format!("could not read agent document {}", file.display()),
                )
                .with_context(error.to_string())
                .with_help("Pass a readable JSON document generated by `quirl agent`")
            })?;
            let catalog = installed_agent_catalog(catalog)?;
            let anchors = AgentValidationAnchors::from(&catalog);
            let report = validate_agent_document_with_anchors(&source, kind.into(), Some(&anchors));
            match format {
                AgentOutputFormat::Json => print_json(&report)?,
                AgentOutputFormat::Text => print_validation(&file, &report),
            }
            Ok(i32::from(!report.valid))
        }
    }
}

pub fn installed_agent_catalog(catalog: &Catalog) -> Result<AgentCatalog, ShellError> {
    build_agent_catalog(catalog, &installed_host_api(), env!("CARGO_PKG_VERSION"))
}

fn installed_host_api() -> Vec<HostCapability> {
    HOST_API
        .iter()
        .map(|spec| HostCapability {
            path: spec.path.to_owned(),
            summary: spec.summary.to_owned(),
            parameters: spec
                .parameters
                .iter()
                .map(|parameter| HostParameter {
                    name: parameter.name.to_owned(),
                    value_type: parameter.lua_type.to_owned(),
                })
                .collect(),
            returns: spec.returns.to_owned(),
            capability: spec.capability.map(str::to_owned),
        })
        .collect()
}

fn print_agent_catalog(catalog: &AgentCatalog) {
    println!("Quirl {} agent catalog", catalog.quirl_version);
    println!("catalog schema: {}", catalog.schema_hash);
    println!("catalog content: {}", catalog.catalog_hash);
    println!("host API: {}", catalog.host_api_hash);
    println!("\nCommands:");
    for command in &catalog.commands {
        println!("  {:<32} {}", command.signature, command.summary);
    }
    println!("\nCapabilities:");
    for capability in &catalog.capabilities {
        println!(
            "  {:<24} v{} {}",
            capability.name, capability.version, capability.schema_hash
        );
    }
}

fn print_agent_manifest(manifest: &AgentManifest) {
    println!("Quirl {} installed agent interface", manifest.quirl_version);
    println!("schema: {}", manifest.schema_hash);
    println!("{} tools", manifest.tools.len());
    for tool in &manifest.tools {
        println!("  {:<32} {}", tool.name, tool.summary);
    }
    println!("{} declared capabilities", manifest.capabilities.len());
    for capability in &manifest.capabilities {
        println!("  {} ({})", capability.name, capability.schema_hash);
    }
}

fn print_validation(file: &Path, report: &ValidationReport) {
    if report.valid {
        println!("✓ {} is a valid versioned agent document", file.display());
        return;
    }
    println!(
        "✗ {} has {} diagnostics",
        file.display(),
        report.diagnostics.len()
    );
    for diagnostic in &report.diagnostics {
        println!(
            "  {} at {}: {}\n    help: {}",
            diagnostic.code, diagnostic.path, diagnostic.message, diagnostic.help
        );
    }
}

fn print_json(value: &impl Serialize) -> Result<(), ShellError> {
    println!(
        "{}",
        serde_json::to_string_pretty(value).map_err(|error| {
            ShellError::new(ErrorCode::Io, "could not serialize agent output")
                .with_context(error.to_string())
                .with_help("Report this as a Quirl agent schema defect")
        })?
    );
    Ok(())
}

impl From<AgentKind> for AgentDocumentKind {
    fn from(kind: AgentKind) -> Self {
        match kind {
            AgentKind::Catalog => Self::Catalog,
            AgentKind::Context => Self::Context,
            AgentKind::Manifest => Self::Manifest,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn host_api_adapter_preserves_installed_capabilities() {
        let api = installed_host_api();
        assert!(api.iter().any(|spec| {
            spec.path == "quirl.process.run" && spec.capability.as_deref() == Some("process.spawn")
        }));
    }

    #[test]
    fn clap_requires_agent_validation_kind() {
        use clap::Parser;

        assert!(
            crate::Cli::try_parse_from(["quirl", "agent", "validate", "catalog.json"]).is_err()
        );
        assert!(crate::Cli::try_parse_from([
            "quirl",
            "agent",
            "validate",
            "catalog.json",
            "--kind",
            "catalog"
        ])
        .is_ok());
    }
}
