[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
clap.workspace = true
color-eyre.workspace = true
quirl-catalog = { path = "../crates/quirl-catalog" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
xshell.workspace = true
unicode-width.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["fs", "poll"] }

[lints]
workspace = true
