[package]
name = "quirl-cli"
description = "The Quirl shell"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "quirl"
path = "src/main.rs"

[dependencies]
clap.workspace = true
quirl-catalog = { path = "../quirl-catalog" }
quirl-core = { path = "../quirl-core" }
quirl-data = { path = "../quirl-data" }
quirl-lua = { path = "../quirl-lua" }
quirl-syntax = { path = "../quirl-syntax" }
quirl-ui = { path = "../quirl-ui" }
reedline.workspace = true
serde_json.workspace = true
